name: ct484_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: any
  flutter_dotenv: any
  image_picker: any
  http_parser: any
  path : any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    -  .env
    - assets/header-images/logo.jpg
    - assets/header-images/banner.jpg
    - assets/header-images/iconFvr.png
    - assets/header-images/iconGiohang.png
    - assets/header-images/homelogo.png
    - assets/header-images/Fvrlogo.png
    - assets/header-images/shopinglogo.png
    - assets/header-images/editicon.png
    - assets/header-images/backicon.png
    - assets/header-images/addcart.png
    - assets/header-images/banner2.jpg
    - assets/header-images/nendevices.png
    - assets/header-images/nenlap.png
    - assets/header-images/nenphone.png
    - assets/header-images/minus.png
    - assets/header-images/add.png
    - assets/header-images/avatar.jpg
    - assets/header-images/logout.png
   
